// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficJam.Api.Data;

#nullable disable

namespace TrafficJam.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902120000_AddDevLoginDemoAccounts")]
    partial class AddDevLoginDemoAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@trafficjam.life",
                            Name = "Traffic Jam Admin",
                            PasswordHash = "210000.sBvGgNG4BNIZo1TOLt0P1w==.D8IqhFYqaSICrUItAR/LrOUjll5Rjayp7mZtdppxldE="
                        });
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("PreferredDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("PreferredTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.BirthData", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Dob")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lng")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tob")
                        .HasColumnType("longtext");

                    b.Property<bool>("UnknownTime")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("BirthData");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Chart", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Ayanamsa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CuspJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("D10Json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("D1Json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("D60Json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("D9Json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KpJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoonJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nakshatra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Charts");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.ConsultPlanRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PriceRupees")
                        .HasColumnType("bigint");

                    b.Property<int>("SlaHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConsultPlanRows");

                    b.HasData(
                        new
                        {
                            Id = "standard",
                            Name = "Standard",
                            PriceRupees = 99L,
                            SlaHours = 4
                        },
                        new
                        {
                            Id = "priority",
                            Name = "Priority",
                            PriceRupees = 299L,
                            SlaHours = 1
                        });
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.DailySignal", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BreakdownJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("UserId", "Date");

                    b.ToTable("DailySignals");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Dasha", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AntarJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MahaJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PratyantarJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("ValidMonth")
                        .HasColumnType("date");

                    b.HasKey("UserId");

                    b.ToTable("Dashas");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Read")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.NotificationPrefs", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ChannelsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Dasha")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Events")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Morning")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RahuKaal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Remedies")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserId");

                    b.ToTable("NotificationPrefs");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.OnboardingDraft", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Dob")
                        .HasColumnType("longtext");

                    b.Property<string>("Lat")
                        .HasColumnType("longtext");

                    b.Property<string>("Lng")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Place")
                        .HasColumnType("longtext");

                    b.Property<string>("Timezone")
                        .HasColumnType("longtext");

                    b.Property<string>("Tob")
                        .HasColumnType("longtext");

                    b.Property<bool>("UnknownTime")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("OnboardingDrafts");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.PanchangCache", b =>
                {
                    b.Property<string>("City")
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("AbhijitEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("AbhijitStart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GulikaKaalEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GulikaKaalStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Karana")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("KaranaEndsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Moonrise")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Moonset")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nakshatra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NakshatraEndsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Paksha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RahuKaalEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RahuKaalStart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Sunrise")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Sunset")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tithi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TithiEndsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("YamagandaKaalEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("YamagandaKaalStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Yoga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("YogaEndsAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("City", "Date");

                    b.ToTable("PanchangCache");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SlaAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.RemedyContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TriggerRule")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RemedyContent");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4fdf37fa-09d9-498b-9e4c-5a0779a374fb"),
                            Detail = "Begin each day with a few quiet minutes of reflection or meditation before checking your phone.",
                            Title = "Start the day before the phone does",
                            TriggerRule = "general",
                            Type = "lifestyle"
                        },
                        new
                        {
                            Id = new Guid("fa9359ab-7970-466b-a528-713dc3863f3f"),
                            Detail = "Noting three things you're grateful for each day steadies the mind regardless of which planet is active. These are general, traditional practices — for anything specific to your own chart, ask Jay.",
                            Title = "Keep a gratitude journal",
                            TriggerRule = "general",
                            Type = "lifestyle"
                        },
                        new
                        {
                            Id = new Guid("dc9edf2b-75ed-430d-b513-45fc88aa532b"),
                            Detail = "Chant \"Om Suryaya Namah\" 108 times facing east at sunrise, and offer water (Arghya) to the rising sun.",
                            Title = "Surya mantra at sunrise",
                            TriggerRule = "Sun",
                            Type = "mantra"
                        },
                        new
                        {
                            Id = new Guid("6ee467c9-cd22-4702-b341-8ac21926a9dc"),
                            Detail = "Donate wheat or jaggery on Sundays — Surya's day rewards discipline, vitality and giving back.",
                            Title = "Sunday giving",
                            TriggerRule = "Sun",
                            Type = "charity"
                        },
                        new
                        {
                            Id = new Guid("afaf592c-af6e-4613-8f02-a2a4ef461285"),
                            Detail = "Chant \"Om Chandraya Namah\" on Monday evenings to steady the mind and emotions.",
                            Title = "Chandra mantra on Monday",
                            TriggerRule = "Moon",
                            Type = "mantra"
                        },
                        new
                        {
                            Id = new Guid("064bc2b6-c738-4fd3-8b69-18d54bb4a343"),
                            Detail = "Keep a regular sleep schedule near the full and new moon, and donate rice or milk on Mondays.",
                            Title = "Protect your sleep around the full and new moon",
                            TriggerRule = "Moon",
                            Type = "lifestyle"
                        },
                        new
                        {
                            Id = new Guid("2ba89fb9-13c2-4247-9999-6ac7ebe613e5"),
                            Detail = "Chant \"Om Angarakaya Namah\" 108 times on Tuesdays to channel Mars' energy constructively.",
                            Title = "Mangal mantra on Tuesday",
                            TriggerRule = "Mars",
                            Type = "mantra"
                        },
                        new
                        {
                            Id = new Guid("833d0c04-19fa-462a-8e61-fff2aca3a27f"),
                            Detail = "Donate red lentils (masoor dal) or jaggery on Tuesdays, and avoid starting conflicts on this day.",
                            Title = "Tuesday giving, and a calmer temper",
                            TriggerRule = "Mars",
                            Type = "charity"
                        },
                        new
                        {
                            Id = new Guid("01a9d48d-f672-4f1b-bf28-85f904be726e"),
                            Detail = "Chant \"Om Budhaya Namah\" on Wednesdays to support clear thinking and communication.",
                            Title = "Budha mantra on Wednesday",
                            TriggerRule = "Mercury",
                            Type = "mantra"
                        },
                        new
                        {
                            Id = new Guid("12a6bc09-182f-4b55-85b2-045cb2f82816"),
                            Detail = "Donate green moong dal or books on Wednesdays, and feed green vegetables to cows if you can.",
                            Title = "Wednesday giving",
                            TriggerRule = "Mercury",
                            Type = "charity"
                        },
                        new
                        {
                            Id = new Guid("ea045864-241c-4b73-87d5-c7e9d9a3d4d7"),
                            Detail = "Chant \"Om Gram Grim Graum Sah Gurave Namah\" on Thursdays to invite Jupiter's wisdom and growth.",
                            Title = "Guru mantra on Thursday",
                            TriggerRule = "Jupiter",
                            Type = "mantra"
                        },
                        new
                        {
                            Id = new Guid("acbd1d3f-e302-46b9-b46b-6c4858e1eca2"),
                            Detail = "Donate turmeric, chana dal, or yellow items to teachers or those in need on Thursdays.",
                            Title = "Thursday giving",
                            TriggerRule = "Jupiter",
                            Type = "charity"
                        },
                        new
                        {
                            Id = new Guid("69ce6858-5b47-4fe0-a38e-3d457c1787d3"),
                            Detail = "Chant \"Om Shukraya Namah\" on Fridays to support love, beauty and harmony.",
                            Title = "Shukra mantra on Friday",
                            TriggerRule = "Venus",
                            Type = "mantra"
                        },
                        new
                        {
                            Id = new Guid("16e4c981-c631-4bad-acc4-6dee8a6c5e3b"),
                            Detail = "Donate white items (rice, sugar, clothing) on Fridays, and keep your living space clean and pleasant.",
                            Title = "A little more beauty on Friday",
                            TriggerRule = "Venus",
                            Type = "lifestyle"
                        },
                        new
                        {
                            Id = new Guid("99fba551-965e-4d17-ad79-7c8f36ace740"),
                            Detail = "Chant \"Om Sham Shanicharaya Namah\" on Saturdays — Saturn rewards patience, discipline and humility.",
                            Title = "Shani mantra on Saturday",
                            TriggerRule = "Saturn",
                            Type = "mantra"
                        },
                        new
                        {
                            Id = new Guid("17e0d927-0c28-467f-8514-31b1994e77fc"),
                            Detail = "Donate mustard oil or black sesame seeds, or spend some time serving others on Saturdays.",
                            Title = "Saturday service",
                            TriggerRule = "Saturn",
                            Type = "charity"
                        },
                        new
                        {
                            Id = new Guid("0dc6a08b-c4e6-4c8e-824a-d32be7240095"),
                            Detail = "Chant \"Om Rahave Namah\" on Saturdays, and avoid major decisions during Rahu Kaal.",
                            Title = "Rahu mantra on Saturday",
                            TriggerRule = "Rahu",
                            Type = "mantra"
                        },
                        new
                        {
                            Id = new Guid("21091c89-b8e0-443e-9e2b-5a416a70e3dd"),
                            Detail = "Donate blankets or dark-coloured grains to those in need — a grounding counterweight to Rahu's ambition.",
                            Title = "Grounding Rahu's restlessness",
                            TriggerRule = "Rahu",
                            Type = "charity"
                        },
                        new
                        {
                            Id = new Guid("6d37ff62-789f-4468-8f11-a944da36c44b"),
                            Detail = "Chant \"Om Ketave Namah\", or a Ganesha mantra — classically believed to pacify Ketu's influence.",
                            Title = "Ketu mantra",
                            TriggerRule = "Ketu",
                            Type = "mantra"
                        },
                        new
                        {
                            Id = new Guid("32a7bbda-6a38-4e8d-9c43-249029eab11c"),
                            Detail = "Set aside time for meditation or spiritual study, and consider giving anonymously when you can.",
                            Title = "Quiet time for Ketu",
                            TriggerRule = "Ketu",
                            Type = "lifestyle"
                        });
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Subscription", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GatewayRef")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RenewsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Cycle = "Monthly",
                            GatewayRef = "demo-seed",
                            RenewsAt = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Tier = "SagaPlus"
                        },
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Cycle = "Yearly",
                            GatewayRef = "demo-seed",
                            RenewsAt = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Tier = "SagaPlus"
                        });
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.SubscriptionPlanRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PriceRupees")
                        .HasColumnType("bigint");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlanRows");

                    b.HasData(
                        new
                        {
                            Id = "free",
                            Cycle = "None",
                            FeaturesJson = "[\"Daily Traffic Signal\",\"Basic Panchang\"]",
                            Name = "Free",
                            PriceRupees = 0L,
                            Tier = "Free"
                        },
                        new
                        {
                            Id = "saga_plus_monthly",
                            Cycle = "Monthly",
                            FeaturesJson = "[\"Deep-space transits\",\"Unlimited Panchang\",\"Priority Ask Jay\"]",
                            Name = "Saga+ Monthly",
                            PriceRupees = 299L,
                            Tier = "SagaPlus"
                        },
                        new
                        {
                            Id = "saga_plus_annual",
                            Cycle = "Yearly",
                            FeaturesJson = "[\"Deep-space transits\",\"Unlimited Panchang\",\"Priority Ask Jay\",\"2 months free\"]",
                            Name = "Saga+ Annual",
                            PriceRupees = 2999L,
                            Tier = "SagaPlus"
                        });
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("PhoneHash")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirebaseUid = "dev:+919999900001",
                            Name = "Demo (Free)",
                            PhoneHash = "2ec2c1d2994802d3bba5aa6e697c7d132bcdf9a5c4c5af59a5a9c5e428fedf1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirebaseUid = "dev:+919999900002",
                            Name = "Demo (Saga+ Monthly)",
                            PhoneHash = "6a6cbd5fd6f9a693465f6dc2f36698de2502492eec8c4c739cc214b82c02dfe"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirebaseUid = "dev:+919999900003",
                            Name = "Demo (Saga+ Annual)",
                            PhoneHash = "6acfb35b135a02360298fcb372d6672718fb65c1f36cfcb396012deaea2a89a"
                        });
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Appointment", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.BirthData", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithOne("BirthData")
                        .HasForeignKey("TrafficJam.Api.Data.Entities.BirthData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Chart", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithOne("Chart")
                        .HasForeignKey("TrafficJam.Api.Data.Entities.Chart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.DailySignal", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithMany("DailySignals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Dasha", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithOne("Dasha")
                        .HasForeignKey("TrafficJam.Api.Data.Entities.Dasha", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Device", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Message", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.Question", "Question")
                        .WithMany("Messages")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Notification", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.NotificationPrefs", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithOne("NotificationPrefs")
                        .HasForeignKey("TrafficJam.Api.Data.Entities.NotificationPrefs", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.OnboardingDraft", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithOne("OnboardingDraft")
                        .HasForeignKey("TrafficJam.Api.Data.Entities.OnboardingDraft", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Question", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Subscription", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("TrafficJam.Api.Data.Entities.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Question", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BirthData");

                    b.Navigation("Chart");

                    b.Navigation("DailySignals");

                    b.Navigation("Dasha");

                    b.Navigation("Devices");

                    b.Navigation("NotificationPrefs");

                    b.Navigation("Notifications");

                    b.Navigation("OnboardingDraft");

                    b.Navigation("Questions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
