// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficJam.Api.Data;

#nullable disable

namespace TrafficJam.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.BirthData", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Dob")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lng")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tob")
                        .HasColumnType("longtext");

                    b.Property<bool>("UnknownTime")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("BirthData");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Chart", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Ayanamsa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CuspJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("D10Json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("D1Json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("D60Json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("D9Json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KpJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoonJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nakshatra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Charts");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.DailySignal", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BreakdownJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("UserId", "Date");

                    b.ToTable("DailySignals");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Dasha", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AntarJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MahaJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PratyantarJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("ValidMonth")
                        .HasColumnType("date");

                    b.HasKey("UserId");

                    b.ToTable("Dashas");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Read")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.NotificationPrefs", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ChannelsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Dasha")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Events")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Morning")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RahuKaal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Remedies")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserId");

                    b.ToTable("NotificationPrefs");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.OnboardingDraft", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Dob")
                        .HasColumnType("longtext");

                    b.Property<string>("Lat")
                        .HasColumnType("longtext");

                    b.Property<string>("Lng")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Place")
                        .HasColumnType("longtext");

                    b.Property<string>("Timezone")
                        .HasColumnType("longtext");

                    b.Property<string>("Tob")
                        .HasColumnType("longtext");

                    b.Property<bool>("UnknownTime")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("OnboardingDrafts");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.PanchangCache", b =>
                {
                    b.Property<string>("City")
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("AbhijitEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("AbhijitStart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GulikaKaalEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GulikaKaalStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Karana")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("KaranaEndsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Moonrise")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Moonset")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nakshatra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NakshatraEndsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Paksha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RahuKaalEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RahuKaalStart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Sunrise")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Sunset")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tithi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TithiEndsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("YamagandaKaalEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("YamagandaKaalStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Yoga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("YogaEndsAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("City", "Date");

                    b.ToTable("PanchangCache");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SlaAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.RemedyContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TriggerRule")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RemedyContent");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Subscription", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GatewayRef")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RenewsAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("PhoneHash")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.BirthData", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithOne("BirthData")
                        .HasForeignKey("TrafficJam.Api.Data.Entities.BirthData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Chart", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithOne("Chart")
                        .HasForeignKey("TrafficJam.Api.Data.Entities.Chart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.DailySignal", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithMany("DailySignals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Dasha", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithOne("Dasha")
                        .HasForeignKey("TrafficJam.Api.Data.Entities.Dasha", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Device", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Message", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.Question", "Question")
                        .WithMany("Messages")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Notification", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.NotificationPrefs", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithOne("NotificationPrefs")
                        .HasForeignKey("TrafficJam.Api.Data.Entities.NotificationPrefs", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.OnboardingDraft", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithOne("OnboardingDraft")
                        .HasForeignKey("TrafficJam.Api.Data.Entities.OnboardingDraft", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Question", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Subscription", b =>
                {
                    b.HasOne("TrafficJam.Api.Data.Entities.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("TrafficJam.Api.Data.Entities.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.Question", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TrafficJam.Api.Data.Entities.User", b =>
                {
                    b.Navigation("BirthData");

                    b.Navigation("Chart");

                    b.Navigation("DailySignals");

                    b.Navigation("Dasha");

                    b.Navigation("Devices");

                    b.Navigation("NotificationPrefs");

                    b.Navigation("Notifications");

                    b.Navigation("OnboardingDraft");

                    b.Navigation("Questions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
